modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/todust-dev/Chunksmith-GUI/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
displayURL="https://github.com/BarryAlen777/Chunksmith_modern_gui"
logoFile="logo.png"
description='''Chunksmith modern gui —— 为 Chunksmith 前置模组提供现代化图形面板。

作者：BarryAlen777
开源地址：https://github.com/BarryAlen777/Chunksmith_modern_gui'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
